Check if locale needs to be updated (#4819)
* Check if locale needs to be updated

* Update message

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -35,6 +35,15 @@ jobs:
         run: npm ci
       - name: Linting Application
         run: npm run lint
+      - name: Checking if locale is updated
+        run: |-
+          npm run locale:extract
+          if [ "$(git diff --name-only)" ]; then
+            echo ""
+            echo "ERROR! Locale file update detected!  Please run 'npm run locale:update'."
+            echo ""
+            exit 1
+          fi
 
   build:
     runs-on: ubuntu-latest
